# Generated by Django 3.1.4 on 2020-12-21 05:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rds', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='students',
            new_name='student',
        ),
    ]
