# Generated by Django 3.1.4 on 2020-12-21 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rds', '0002_auto_20201221_1109'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='blood_group',
            field=models.CharField(default='SOME STRING', max_length=5),
        ),
        migrations.AddField(
            model_name='student',
            name='cell_phone',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='student',
            name='citizenship',
            field=models.CharField(default='SOME STRING', max_length=20),
        ),
        migrations.AddField(
            model_name='student',
            name='credits_passed',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='student',
            name='current_cgpa',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='student',
            name='current_status',
            field=models.CharField(default='SOME STRING', max_length=50),
        ),
        migrations.AddField(
            model_name='student',
            name='curriculum_name',
            field=models.CharField(default='SOME STRING', max_length=100),
        ),
        migrations.AddField(
            model_name='student',
            name='enrolled_in',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='student',
            name='entry_item',
            field=models.CharField(default='SOME STRING', max_length=100),
        ),
        migrations.AddField(
            model_name='student',
            name='fathers_name',
            field=models.CharField(default='SOME STRING', max_length=50),
        ),
        migrations.AddField(
            model_name='student',
            name='guardian_name',
            field=models.CharField(default='SOME STRING', max_length=50),
        ),
        migrations.AddField(
            model_name='student',
            name='mailing_address',
            field=models.CharField(default='SOME STRING', max_length=200),
        ),
        migrations.AddField(
            model_name='student',
            name='major_1',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='student',
            name='major_2',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='student',
            name='marital_status',
            field=models.CharField(default='SOME STRING', max_length=10),
        ),
        migrations.AddField(
            model_name='student',
            name='mothers_name',
            field=models.CharField(default='SOME STRING', max_length=50),
        ),
        migrations.AddField(
            model_name='student',
            name='parent_address',
            field=models.CharField(default='SOME STRING', max_length=200),
        ),
        migrations.AddField(
            model_name='student',
            name='parent_phone',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='student',
            name='personal_email',
            field=models.CharField(default='SOME STRING', max_length=100),
        ),
        migrations.AddField(
            model_name='student',
            name='probation',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='student',
            name='sex',
            field=models.CharField(default='SOME STRING', max_length=10),
        ),
        migrations.AddField(
            model_name='student',
            name='telephone',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='student',
            name='test_pass_number',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='student',
            name='firstname',
            field=models.CharField(default='SOME STRING', max_length=100),
        ),
        migrations.AlterField(
            model_name='student',
            name='lastname',
            field=models.CharField(default='SOME STRING', max_length=100),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_id',
            field=models.IntegerField(default=0),
        ),
    ]
